### ISSUE TITLE
NameError: name '_mysql' is not defined

### ISSUE THREAD

**Issue by mattjmeier** [BU-ISCIII/iSkyLIMS#17]
Hello,

I am trying to set up iSkyLIMS on Ubuntu (20.04).

I've been able to accomplish all the steps and installed all system and environment dependencies as far as I can tell (pip freeze shows everything required). However, I keep getting the same result at the end when I launch `python manage.py runserver 0:8083`:

`
 Exception ignored in thread started by: <function check_errors.<locals>.wrapper at 0x7f1c65952b80>
Traceback (most recent call last):
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/iSkyLIMS/iSkyLIMS_wetlab/models.py", line 7, in <module>
    from django.contrib.auth.models import User
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/db/models/base.py", line 114, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/db/models/base.py", line 315, in add_to_class
    value.contribute_to_class(cls, name)
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/db/models/options.py", line 205, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/db/utils.py", line 202, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
  File "/srv/iSkyLIMS/virtualenv/lib/python3.8/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
`

It's very strange because I have followed all the documentation precisely. But I suspect this doesn't preclude this possibility that my system configuration has some differences from what's expected. Any help is appreciated in interpreting the errors!

Thank you
Matt

**Comment by moonjo-geno** [comment]
I think the documentation is a bit outdated. You might have to update the configuration. But, I'm just guessing as I'm also trying to check out the tool.

**Comment by luissian** [comment]
Hi Moonjo.
Documentation is, as you said, outdated. But for master release, the installation instruction should work fine. We have never get the error mattjmeier describe above..
Sorry mattjmeier, for not reply you before. Could you please check that you mysal database is up?

We are working o an new version of iSkyLIMS, with a new module structure, to help us to add, in the feature, new functionality. 
As we are still working on coding, and changes for adding latest functionality impact impact on documentation and installation procedure,  we have decided to stop the documentation guide that is on readthedocs :
But you can have a look to see what is new on the new version that we are planned to release in October this year.
https://iskylims.readthedocs.io/en/latest/index.html

**Comment by luissian** [comment]
New documentation and installation instructions will be provided for iSkyLIMS version 2.0.
This new version will be released soon
