### ISSUE TITLE
Parameter name in pipeline error

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iskylims#190]
### Description of the bug

When defining a new pipeline, if paramters are added, an error appears:

```
Environment:

Request Method: POST
Request URL: http://iskylims.isciiides.es/drylab/define-pipeline

Django Version: 3.2
Python Version: 3.9.6
Installed Applications:
['core',
 'wetlab',
 'drylab',
 'django_utils',
 'mptt',
 'crispy_forms',
 'crispy_bootstrap5',
 'django_crontab',
 'django_mptt_admin',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'rest_framework',
 'drf_yasg',
 'django_cleanup']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/iskylims/drylab/views.py", line 1602, in define_pipeline
    drylab.utils.pipelines.store_parameters_pipeline(
  File "/opt/iskylims/drylab/utils/pipelines.py", line 257, in store_parameters_pipeline
    drylab.models.ParameterPipeline.objects.create_pipeline_parameters(
  File "/opt/iskylims/drylab/models.py", line 176, in create_pipeline_parameters
    parameter_name=pipeline_parameters["parameter_name"],

Exception Type: KeyError at /drylab/define-pipeline
Exception Value: 'parameter_name'
```

![Screenshot from 2023-07-19 12-52-49](https://github.com/BU-ISCIII/iskylims/assets/25959991/e5f83d56-77f1-45ea-8acb-02478dda0926)

BUT the pipeline is being created even so.

**Comment by luissian** [comment]
Changed in pipelines.py the variable from parameterName to parameter_name
