### ISSUE TITLE
Swagger not working

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iskylims#193]
### Description of the bug

When performing a GET request to drylab_api_serviceFullData_list, the following error appears:

```
Traceback (most recent call last):
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/iskylims/drylab/api/views.py", line 244, in service_full_data
    service_full_data = ServiceSerializer(service_obj, many=False).data
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/opt/iskylims/drylab/api/serializers.py", line 271, in to_representation
    output_label = self.context["output_label"]

Exception Type: KeyError at /drylab/api/serviceFullData
Exception Value: 'output_label'
Request information:
USER: bioinfoadm
```

**Comment by saramonzon** [comment]
Fixed #194
