### ISSUE TITLE
Run status gives error because capitalization

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iSkyLIMS#279]
### Description of the bug

When opening a run stats in wetlab, the following error appears:
```
ValueError at /wetlab/displayRun=13926/
'Completed' is not in list
Request Method:	GET
Request URL:	http://iskylims.isciiides.es/wetlab/displayRun%3D13926/
Django Version:	4.2.7
Exception Type:	ValueError
Exception Value:	
'Completed' is not in list
Exception Location:	/opt/iskylims/wetlab/utils/fetch_info.py, line 231, in graphics_state
Raised during:	wetlab.views.display_run
Python Executable:	/opt/iskylims/virtualenv/bin/python
Python Version:	3.9.6
Python Path:	
['/opt/iskylims',
 '/opt/python/3.9.6/lib/python39.zip',
 '/opt/python/3.9.6/lib/python3.9',
 '/opt/python/3.9.6/lib/python3.9/lib-dynload',
 '/opt/iskylims/virtualenv/lib/python3.9/site-packages']
Server time:	Tue, 20 Aug 2024 09:40:55 +0200
```

```
Traceback (most recent call last):
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/iskylims/virtualenv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/opt/iskylims/wetlab/views.py", line 1223, in display_run
    r_data_display = wetlab.utils.fetch_info.get_information_run(run_name_found)
  File "/opt/iskylims/wetlab/utils/fetch_info.py", line 719, in get_information_run
    info_dict["graphic_value"], info_dict["graphic_color"] = graphics_state(run_state)
  File "/opt/iskylims/wetlab/utils/fetch_info.py", line 231, in graphics_state
    index = state_list.index(state)

Exception Type: ValueError at /wetlab/displayRun=13926/
Exception Value: 'Completed' is not in list
```

```
Local vars
Variable	Value
g_color	
['red', 'violet', 'pink', 'brown', 'orange', 'yellow', 'yellow', 'green', 'red']
g_value	
[10, 15, 30, 45, 60, 75, 90, 100, 10]
state	
'Completed'
state_list	
['error',
 'recorded',
 'sample_sent',
 'processing_run',
 'processed_run',
 'processing_bcl2fastq',
 'processed_bcl2fastq',
 'completed',
 'cancelled']
```

**Comment by luissian** [comment]
It was missing to execute with doing the upgrade the option of updating tables
